import {renderScene} from './renderer.js';
import {COURSES,center,width,newRun,step,jump,grade,score,clamp} from './engine.js';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
let boostQueued=false;let state='menu',selected=0,unlocked=0,run=null,last=0,tilt=0,tiltBase=null,tiltLive=false,tiltAt=0,noticeUntil=0,keys=new Set(),touch={left:false,right:false,brake:false},audio=null;
try{unlocked=clamp(Number(localStorage.getItem('snowline-unlocked'))||0,0,2)}catch{}
function sound(type){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type==='hit'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='fish'?580:type==='hit'?130:380,t);o.frequency.exponentialRampToValueAtTime(type==='fish'?900:type==='hit'?75:510,t+.13);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.085,t+.014);g.gain.exponentialRampToValueAtTime(.0001,t+.16);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.17)}catch{}}
function announce(s){$('notice').textContent=s;noticeUntil=performance.now()+1100}
function picker(){const root=$('picker');root.replaceChildren();COURSES.forEach((c,i)=>{const b=document.createElement('button');b.textContent=`${String(i+1).padStart(2,'0')} ${c.name}`;b.disabled=i>unlocked;b.className=i===selected?'active':'';b.onclick=()=>{selected=i;picker();$('description').textContent=`${c.subtitle}. ${c.gateCount} gates · ${c.target} fish · ${c.time}s par.`};root.append(b)})}
function menu(mode='menu'){state=mode;$('panel').hidden=false;$('controls').hidden=true;$('hud').hidden=true;$('pause').hidden=true;$('panel').querySelector('h1').innerHTML='SNOWLINE<br><em>SPRINT</em>';$('description').textContent='Three alpine descents. Thread the gates, gather fish, and outrun the clock.';$('primary').innerHTML='START DESCENT <span>↗</span>';$('menuButton').hidden=true;picker()}
function start(){run=newRun(selected);tiltBase=null;tiltLive=false;state='racing';$('panel').hidden=true;$('controls').hidden=false;$('hud').hidden=false;$('pause').hidden=false;last=performance.now();announce(COURSES[selected].name.toUpperCase());audio?.resume();requestTilt()}
function requestTilt(){if(typeof DeviceOrientationEvent==='undefined')return;if(typeof DeviceOrientationEvent.requestPermission==='function'){DeviceOrientationEvent.requestPermission().catch(()=>{});} }
window.addEventListener('deviceorientation',e=>{if(typeof e.gamma!=='number')return;if(tiltBase===null)tiltBase=e.gamma;tilt=clamp((e.gamma-tiltBase)/24,-1,1);tiltLive=true;tiltAt=performance.now()});
function finish(){state='results';$('hud').hidden=true;$('controls').hidden=true;$('pause').hidden=true;$('panel').hidden=false;const win=grade(run);if(win&&selected===unlocked&&unlocked<2){unlocked++;try{localStorage.setItem('snowline-unlocked',String(unlocked))}catch{}}picker();$('panel').querySelector('h1').innerHTML=win?'SUMMIT<br><em>CLEARED</em>':'RUN<br><em>COMPLETE</em>';$('description').textContent=`${COURSES[selected].name} · ${Math.ceil(run.elapsed)}s · ${run.fish} fish · ${run.gates}/${run.course.gateCount} gates · ${run.hits} hits. Score ${score(run)}. ${win?'Next course unlocked.':'Medal: collect target fish, clear 65% of gates, beat par, and take fewer than four hits.'}`;$('primary').innerHTML='RACE AGAIN <span>↗</span>';$('menuButton').hidden=false;sound(win?'fish':'hit')}
$('menuButton').onclick=()=>menu();$('primary').onclick=()=>{if(state==='paused'){state='racing';$('panel').hidden=true;last=performance.now();return}start()};$('pause').onclick=()=>{if(state!=='racing')return;state='paused';$('panel').hidden=false;$('panel').querySelector('h1').innerHTML='TAKE A<br><em>BREATH</em>';$('description').textContent='The mountain waits. Tilt to steer, or use the arrows. Hold brake on tight turns.';$('primary').innerHTML='RESUME <span>↗</span>';$('menuButton').hidden=false};
for(const id of ['left','right','brake']){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[id]=true};b.onpointerup=b.onpointercancel=()=>touch[id]=false}
$('boost').onpointerdown=e=>{e.preventDefault();if(state==='racing')boostQueued=true};
$('jump').onpointerdown=e=>{e.preventDefault();if(state==='racing')jump(run)};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if((e.code==='ArrowUp'||e.code==='KeyW')&&state==='racing'&&!e.repeat)boostQueued=true;if(e.code==='Space'&&state==='racing'&&!e.repeat)jump(run);if(e.code==='Escape'&&state==='racing')$('pause').click()});window.addEventListener('keyup',e=>keys.delete(e.code));
function render(){const c=run?.course||COURSES[selected];renderScene(ctx,run,c,performance.now());if(run){$('timer').textContent=`${Math.floor(run.elapsed/60).toString().padStart(2,'0')}:${Math.floor(run.elapsed%60).toString().padStart(2,'0')}`;$('fishHud').textContent=`◆ ${run.fish}/${c.target}`;$('gateHud').textContent=`◇ ${run.gates}/${c.gateCount}`;$('speedHud').textContent=`${Math.round(run.speed)} m/s`;$('progress').style.width=`${run.z/c.length*100}%`;$('staminaFill').style.width=`${run.stamina}%`;$('boostHud').textContent=`⚡ ${run.boostCharges} BOOST${run.boostCharges===1?'':'S'}`;$('courseHud').textContent=c.name.toUpperCase()}}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(state==='racing'){
 const steer=(touch.right||keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(touch.left||keys.has('ArrowLeft')||keys.has('KeyA')?1:0);
 // Touch/keyboard takes priority while pressed; sensor tilt takes over otherwise.
 step(run,dt,{steer:steer||((tiltLive&&t-tiltAt<1000&&Math.abs(tilt)>.08)?tilt:0),brake:touch.brake||keys.has('ArrowDown')||keys.has('KeyS'),boost:boostQueued});boostQueued=false;
 for(const e of run.events){if(e==='fish'||e==='gate'||e==='hit'||e==='ramp'){announce({fish:'FISH +85',gate:'CLEAN GATE +160',hit:'ROCK! SLOW DOWN',ramp:'AIRBORNE',boost:'BOOST!',charge:'BOOST +1'}[e]);sound(e)}}if(run.finished)finish();}
 if(t>noticeUntil)$('notice').textContent='';render();requestAnimationFrame(frame)}
picker();requestAnimationFrame(frame);
window.__snowline={get state(){return state},get run(){return run},get unlocked(){return unlocked},start,step:(dt,input)=>{if(state==='racing'){step(run,dt,input);if(run.finished)finish()}},jump:()=>jump(run)};
