import {COURSES,center,width,newRun,step,jump,grade,score,clamp} from './engine.js';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
let state='menu',selected=0,unlocked=0,run=null,last=0,tilt=0,tiltBase=null,tiltLive=false,tiltAt=0,noticeUntil=0,keys=new Set(),touch={left:false,right:false,brake:false},audio=null;
try{unlocked=clamp(Number(localStorage.getItem('snowline-unlocked'))||0,0,2)}catch{}
function sound(type){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type==='hit'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='fish'?580:type==='hit'?130:380,t);o.frequency.exponentialRampToValueAtTime(type==='fish'?900:type==='hit'?75:510,t+.13);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.085,t+.014);g.gain.exponentialRampToValueAtTime(.0001,t+.16);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.17)}catch{}}
function announce(s){$('notice').textContent=s;noticeUntil=performance.now()+1100}
function picker(){const root=$('picker');root.replaceChildren();COURSES.forEach((c,i)=>{const b=document.createElement('button');b.textContent=`${String(i+1).padStart(2,'0')} ${c.name}`;b.disabled=i>unlocked;b.className=i===selected?'active':'';b.onclick=()=>{selected=i;picker();$('description').textContent=`${c.subtitle}. ${c.gateCount} gates · ${c.target} fish · ${c.time}s par.`};root.append(b)})}
function menu(mode='menu'){state=mode;$('panel').hidden=false;$('controls').hidden=true;$('hud').hidden=true;$('pause').hidden=true;$('panel').querySelector('h1').innerHTML='SNOWLINE<br><em>SPRINT</em>';$('description').textContent='Three alpine descents. Thread the gates, gather fish, and outrun the clock.';$('primary').innerHTML='START DESCENT <span>↗</span>';$('menuButton').hidden=true;picker()}
function start(){run=newRun(selected);tiltBase=null;tiltLive=false;state='racing';$('panel').hidden=true;$('controls').hidden=false;$('hud').hidden=false;$('pause').hidden=false;last=performance.now();announce(COURSES[selected].name.toUpperCase());audio?.resume();requestTilt()}
function requestTilt(){if(typeof DeviceOrientationEvent==='undefined')return;if(typeof DeviceOrientationEvent.requestPermission==='function'){DeviceOrientationEvent.requestPermission().catch(()=>{});} }
window.addEventListener('deviceorientation',e=>{if(typeof e.gamma!=='number')return;if(tiltBase===null)tiltBase=e.gamma;tilt=clamp((e.gamma-tiltBase)/24,-1,1);tiltLive=true;tiltAt=performance.now()});
function finish(){state='results';$('hud').hidden=true;$('controls').hidden=true;$('pause').hidden=true;$('panel').hidden=false;const win=grade(run);if(win&&selected===unlocked&&unlocked<2){unlocked++;try{localStorage.setItem('snowline-unlocked',String(unlocked))}catch{}}picker();$('panel').querySelector('h1').innerHTML=win?'SUMMIT<br><em>CLEARED</em>':'RUN<br><em>COMPLETE</em>';$('description').textContent=`${COURSES[selected].name} · ${Math.ceil(run.elapsed)}s · ${run.fish} fish · ${run.gates}/${run.course.gateCount} gates · ${run.hits} hits. Score ${score(run)}. ${win?'Next course unlocked.':'Medal: collect target fish, clear 65% of gates, beat par, and take fewer than four hits.'}`;$('primary').innerHTML='RACE AGAIN <span>↗</span>';$('menuButton').hidden=false;sound(win?'fish':'hit')}
$('menuButton').onclick=()=>menu();$('primary').onclick=()=>{if(state==='paused'){state='racing';$('panel').hidden=true;last=performance.now();return}start()};$('pause').onclick=()=>{if(state!=='racing')return;state='paused';$('panel').hidden=false;$('panel').querySelector('h1').innerHTML='TAKE A<br><em>BREATH</em>';$('description').textContent='The mountain waits. Tilt to steer, or use the arrows. Hold brake on tight turns.';$('primary').innerHTML='RESUME <span>↗</span>';$('menuButton').hidden=false};
for(const id of ['left','right','brake']){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[id]=true};b.onpointerup=b.onpointercancel=()=>touch[id]=false}
$('jump').onpointerdown=e=>{e.preventDefault();if(state==='racing')jump(run)};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space'&&state==='racing'&&!e.repeat)jump(run);if(e.code==='Escape'&&state==='racing')$('pause').click()});window.addEventListener('keyup',e=>keys.delete(e.code));
function polygon(points,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<points.length;i++)ctx.lineTo(...points[i]);ctx.closePath();ctx.fill()}
function mountain(t,color,base,amp){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,140);for(let x=0;x<=240;x+=8)ctx.lineTo(x,base-Math.abs(Math.sin(x*.023+t))*amp-Math.abs(Math.sin(x*.071+t))*amp*.44);ctx.lineTo(240,140);ctx.fill()}
function project(z,x){const d=z-(run?.z||0),y=193-d*1.55,scale=1+Math.max(0,d)*.005;return {x:120+(x-center(z,run?.course||COURSES[selected]))*104/scale,y,scale}}
function drawFish(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#ffd778';ctx.beginPath();ctx.ellipse(0,0,4,2.3,0,0,7);ctx.fill();polygon([[3,0],[7,-3],[7,3]],'#ffd778');ctx.fillStyle='#264156';ctx.fillRect(-2,-1,1,1);ctx.restore()}
function drawPenguin(x,y,air=0){ctx.save();ctx.translate(x,y-air*7);ctx.fillStyle='#102a39';ctx.beginPath();ctx.ellipse(0,3,9,12,0,0,7);ctx.fill();ctx.fillStyle='#f5f1dd';ctx.beginPath();ctx.ellipse(0,5,5,7,0,0,7);ctx.fill();ctx.fillStyle='#e9ad57';polygon([[-2,1],[4,1],[0,4]],'#edac50');ctx.fillStyle='#77d4d6';polygon([[-10,-1],[9,-2],[9,0],[-10,1]],'#77d4d6');ctx.fillStyle='#112b36';ctx.fillRect(-3,-3,2,2);ctx.fillRect(3,-3,2,2);ctx.fillStyle='#dfa368';ctx.fillRect(-8,13,7,3);ctx.fillRect(2,13,7,3);ctx.restore()}
function render(){const c=run?.course||COURSES[selected],z=run?.z||0;let sky=ctx.createLinearGradient(0,0,0,180);if(c.theme==='dusk'){sky.addColorStop(0,'#351e45');sky.addColorStop(1,'#d7816a')}else{sky.addColorStop(0,c.theme==='ice'?'#194463':'#1d566b');sky.addColorStop(1,'#91c9c8')}ctx.fillStyle=sky;ctx.fillRect(0,0,240,282);ctx.fillStyle='#f8dfad';ctx.beginPath();ctx.arc(187,49,12,0,7);ctx.fill();mountain(.2,'#5e8c9d',122,30);mountain(1.9,'#345f75',139,18);
 ctx.fillStyle=c.theme==='dusk'?'#d2aabd':'#b9d8d9';ctx.fillRect(0,139,240,143);
 // The visible road is a curved continuous strip in world space, with perspective widening near the rider.
 const left=[],right=[];for(let d=125;d>=-50;d-=5){const zz=Math.max(0,z+d),y=193-d*1.55,w=width(zz,c)*.5,shift=(center(zz,c)-center(z,c))*104;const perspective=80+Math.max(0,125-d)*.4;left.push([120+shift-w*perspective,y]);right.push([120+shift+w*perspective,y]);}
 polygon([...left,...right.reverse()],c.theme==='dusk'?'#f4e8e0':'#edf6ed');ctx.strokeStyle='#80b7bd';ctx.lineWidth=2;for(const side of [-1,1]){ctx.beginPath();for(let d=125;d>=-50;d-=5){const zz=Math.max(0,z+d),y=193-d*1.55,x=120+(center(zz,c)-center(z,c))*104+side*width(zz,c)*.5*(80+Math.max(0,125-d)*.4);if(d===125)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}
 // Deterministic little pines and shadows, drawn procedurally.
 for(let i=0;i<28;i++){const zz=Math.floor(z/30)*30+i*30+20,d=zz-z;if(d<0||d>126)continue;const side=i%2?1:-1,p=project(zz,center(zz,c)+side*(width(zz,c)*.55+.13+(i*7%5)*.045)),h=clamp(16-d*.065,5,16);polygon([[p.x,p.y-h],[p.x-h*.42,p.y],[p.x+h*.42,p.y]],c.theme==='dusk'?'#40546a':'#326879');ctx.fillStyle='#407481';ctx.fillRect(p.x-1,p.y,2,3)}
 if(run){for(const o of run.objects){const d=o.z-z;if(d<0||d>115)continue;const p=project(o.z,o.x),s=clamp(1-d*.006,.35,1);if(o.type==='fish')drawFish(p.x,p.y-5*s,s);else if(o.type==='gate'){const w=14*s;ctx.strokeStyle='#e9925b';ctx.lineWidth=2*s;ctx.beginPath();ctx.moveTo(p.x-w,p.y);ctx.lineTo(p.x-w,p.y-16*s);ctx.moveTo(p.x+w,p.y);ctx.lineTo(p.x+w,p.y-16*s);ctx.stroke();polygon([[p.x-w,p.y-16*s],[p.x+w,p.y-16*s],[p.x+w,p.y-11*s],[p.x-w,p.y-11*s]],'#f5cf7c')}else if(o.type==='rock'){polygon([[p.x-7*s,p.y],[p.x-4*s,p.y-7*s],[p.x+3*s,p.y-9*s],[p.x+8*s,p.y]],'#677d8c')}else{polygon([[p.x-10*s,p.y],[p.x+9*s,p.y],[p.x+4*s,p.y-5*s],[p.x-6*s,p.y-5*s]],'#e8a362')}}
 const dx=(run.x-center(z,c))*95;ctx.fillStyle='#284d6899';ctx.beginPath();ctx.ellipse(120+dx,222,13,4,0,0,7);ctx.fill();drawPenguin(120+dx,208,run.air);$('timer').textContent=`${Math.floor(run.elapsed/60).toString().padStart(2,'0')}:${Math.floor(run.elapsed%60).toString().padStart(2,'0')}`;$('fishHud').textContent=`◆ ${run.fish}/${c.target}`;$('gateHud').textContent=`◇ ${run.gates}/${c.gateCount}`;$('speedHud').textContent=`${Math.round(run.speed)} m/s`;$('progress').style.width=`${run.z/c.length*100}%`; $('courseHud').textContent=c.name.toUpperCase()}
 else drawPenguin(120,205,0);
}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(state==='racing'){
 const steer=(touch.right||keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(touch.left||keys.has('ArrowLeft')||keys.has('KeyA')?1:0);
 // Touch/keyboard takes priority while pressed; sensor tilt takes over otherwise.
 step(run,dt,{steer:steer||((tiltLive&&t-tiltAt<1000&&Math.abs(tilt)>.08)?tilt:0),brake:touch.brake||keys.has('ArrowDown')||keys.has('KeyS')});
 for(const e of run.events){if(e==='fish'||e==='gate'||e==='hit'||e==='ramp'){announce({fish:'FISH +85',gate:'CLEAN GATE +160',hit:'ROCK! SLOW DOWN',ramp:'AIRBORNE'}[e]);sound(e)}}if(run.finished)finish();}
 if(t>noticeUntil)$('notice').textContent='';render();requestAnimationFrame(frame)}
picker();requestAnimationFrame(frame);
window.__snowline={get state(){return state},get run(){return run},get unlocked(){return unlocked},start,step:(dt,input)=>{if(state==='racing'){step(run,dt,input);if(run.finished)finish()}},jump:()=>jump(run)};
